VELOCITY-7584 add optional supports field to releases
UrbanCode/velocity-plugins-index pull request #263
Opened 2022-10-04 16:15 UTC by judaschwartz

2022-10-04 16:39 UTC, aboe026 requested changes

2022-10-04 16:39 UTC, aboe026 commented on src/helpers/ReleasesHelper.js
> +  Supports: '"supports" must have a semver-string whose value is a valid Semantic Version',
```suggestion
  Supports: '"supports" must be a semver-string whose value is a valid Semantic Version',
```

2022-10-04 16:43 UTC, aboe026 submitted a review, later dismissed

2022-10-04 18:25 UTC, aboe026 requested changes

2022-10-04 18:25 UTC, aboe026 commented on test/func/addReleaseTest.js
> +      it('should error if semver is invalid', test(async function() {
```suggestion
      it('should error if supports semver is invalid', test(async function() {
```

2022-10-06 13:42 UTC, jrbarto approved these changes

2022-10-06 15:26 UTC, aboe026 approved these changes

2022-10-06 15:26 UTC, merged